[project]
name = "pong"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {workspace = true}
bevy_egui = "0.17"
leafwing-input-manager = {workspace = true}
bevy_kira_audio = {workspace = true}
